---
- name: Sanz Automation
  hosts: all
  gather_facts: no

  tasks:

  - name: "IOS XR Backup Config"
    cisco.iosxr.iosxr_config:
      config: running-config
      backup: yes
      backup_options:
           filename: config-{{ inventory_hostname }}.txt
           dir_path: /home/sysmin/config/mpls
#    register: runnconfig
#  - debug:
#      var: version.stdout_lines

#  - name: "Parsing Backup"
#    copy:
#      content: "{{ runnconfig.stdout[0] }}"
#      dest: "/home/ansible/Config/config-{{ inventory_hostname }}.txt"
